name: changelog entry

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled, reopened]

permissions:
  contents: read

jobs:
  check-changelog-entry:
    name: Check for changelog entry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Set up environment
        uses: ./.github/actions/setup-env
        with:
          python-version: '3.9'
          nox-setup: "tools"

      - run: python -m pip install towncrier

      - name: Check for presence of a Change Log fragment (only pull requests)
        if: contains(github.event.pull_request.labels.*.name, 'skip news') != true
        # NOTE: The pull request' base branch needs to be fetched so towncrier
        # is able to compare the current branch with the base branch.
        run: |
          if ! towncrier check --compare-with origin/${BASE_BRANCH}; then
            echo "::error::Please see https://github.com/DisnakeDev/disnake/blob/master/changelog/README.rst for details on how to create a changelog entry." >&2
            exit 1
          fi
        env:
          BASE_BRANCH: ${{ github.base_ref }}
